### PR TITLE
Added sphinx documentation

### PR DESCRIPTION
**Pull request by Rambatino**

### CODE REVIEW

**Comment by xulaus** [comment]
Not really a fan of having the build directory committed. If it can be easily regenerated I think it should be left out, perhaps even added to `.gitignore`

**Comment by Rambatino** [comment]
Agreed. Will sort it out on the train in a sec

**Comment by xulaus** [comment]
:+1:

**Comment by Rambatino** [comment]
I've decided against all of this. Will reconvene on Monday about a better way to achieve this.

**Pull request closed without merging**
