### PR TITLE
Add a new max_splits parameter; make a couple of fix updates

### PR DESCRIPTION
**Pull request by jihaekor**
This adds a new `max_splits` parameter, which forces the best split computation to continue (similar to the `min_child_node_size` parameter) until the number of split groups left is at most equal to `max_splits`.

The basic use case for this to limit the number of splits at each split decision, in an effort to keep the size of the trees manageable while merging the "most similar" categories together to achieve this goal.

As a part of the change, I also added in the ability to specify minimum node sizes as fractions, defined as range (0, 1), with open intervals used on both ends.

I also made a couple of fixes that I noticed:
- I removed the duplicate `sufficient_split` check that never gets used in `best_con_split`, original lines 211-214.
- I added a `PURE_NODE` check into the `best_con_split` function, that mimics the same in `best_cat_heuristic_split` (new lines 203-204).

I hope you find the new parameter interesting enough that you would find it useful to get this PR merged.

In terms of the version: Given that this introduces a new parameter, I updated the minor version rather than the patch version; however, do let me know if you would prefer the version to be updated as just a patch, and I can make that adjustment.

### CODE REVIEW

**Comment by jihaekor** [comment]
Hi @Rambatino - I wanted to ping you to see if you had interest in merging this PR. Thanks!

**Comment by Rambatino** [comment]
Hi @jihaekor, very sorry for being slow! Will review later today :)

**Review by Rambatino — APPROVED** [review]

**Comment by jihaekor** [comment]
Hi @Rambatino - Thank you! Was this pushed out to pypi as well?

Also, do you mind taking a quick look at the issue that I opened as well? I will be happy to submit a PR for it based on your thoughts.

Thanks!

**Comment by Rambatino** [comment]
Thanks @jihaekor, I think I commented. But feel free to push a PR to fix, as I don't know if I'm honest. 
It should be pushed to pypi, let me know if any issues :)

**Pull request merged**
