### PR TITLE
Added min_child_node_sixe for both weighted and unweighted case

### PR DESCRIPTION
**Pull request by Rambatino**

### CODE REVIEW

**Comment by Rambatino** [comment]
@xulaus which bit? The bit I rebased on top (which is the refactor) or the min base size stuff? Does it need much more testing?

**Comment by xulaus** [comment]
The refactor stuff has only been tested by me, as its such a substantial change it should have a lot of data ran over it to be 100% sure its working as it should.

**Comment by Rambatino** [comment]
Okay cool!

**Comment by xulaus** [comment]
I also know there is at least one bug on the ordinal variable branch, which I think was introduced later, but you know - need to be sure.

**Pull request merged**
